# Default configuration for paths and parameters

paths:
  data_dir: ./vuljit/datasets
  outputs_dir: ./vuljit/datasets/derived_artifacts
  metrics_dir: ./vuljit/datasets/metric_inputs
  intermediate_dir: ./vuljit/datasets/derived_artifacts/intermediate
  cloned_repos_dir: ./vuljit/datasets/derived_artifacts/intermediate/cloned_repos
  srcmap_dir: ./vuljit/datasets/raw/srcmap_json
  coverage_dir: ./vuljit/datasets/raw/coverage_gz

downloads:
  csv: ./vuljit/datasets/raw/oss_fuzz_vulns.csv
  start_date: 20181012
  end_date: 20250802
  workers: 8
  coverage_files:
    - summary.json
